### ISSUE TITLE
In getSerialBytes() the end return result.decode() crashes 

### ISSUE THREAD

**Issue by chanakyan** [radarjd/sparki_learning#3]
Error :'utf-8' codec can't decode byte'

Python version 3.10

**Comment by radarjd** [comment]
Could you please share what platform you're on? Also, what version of pyserial are you using?

**Comment by chanakyan** [comment]
py serial version is : pyserial 3.5
This is on windows 11

Thank you for the work you have done!

**Comment by radarjd** [comment]
It's my pleasure.

Is this happening on every command (including initial connection) or just certain commands?

**Comment by chanakyan** [comment]
Only on the init call. I have not checked other calls.

It seems that result.encode() fails if result is 0xff. I replaced it with
str(result) and it started working.

I use BT serial ports..

**Comment by radarjd** [comment]
Okay, so Sparki should never send 0xff -- I've got a hypothesis, though. Have you, by any chance, loaded sparki_name_util.ino on to your Sparki? To run it, you open the sparki_name_util.ino in sparkiduino and load it onto the robot. Once it runs a single time, you put sparki_myro.ino back on.

My hypothesis is that the 0xff is coming from a byte that sparki is reading from it's ROM when it tries to read the name of the Sparki. 

It's also possible that I need to improve the error handling in getSerialBytes(). Again, there should never be an 0xff to begin with...

Thanks so much for helping debug this.

**Comment by chanakyan** [comment]
i did that and am still getting this error:

  File "C:\Users\vraje\PycharmProjects\sparki\main.py", line 3, in <module>
    init(com_port, print_versions=True, auto=False, retries=2)
  File
"C:\Users\vraje\anaconda3\envs\sparki\lib\site-packages\sparki_learning-1.6.8-py3.10.egg\sparki_learning\sparki_myro.py",
line 1169, in init
  File
"C:\Users\vraje\anaconda3\envs\sparki\lib\site-packages\sparki_learning-1.6.8-py3.10.egg\sparki_learning\sparki_myro.py",
line 941, in getName
  File
"C:\Users\vraje\anaconda3\envs\sparki\lib\site-packages\sparki_learning-1.6.8-py3.10.egg\sparki_learning\sparki_myro.py",
line 248, in getSerialString
  File
"C:\Users\vraje\anaconda3\envs\sparki\lib\site-packages\sparki_learning-1.6.8-py3.10.egg\sparki_learning\sparki_myro.py",
line 181, in getSerialBytes
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0:
invalid start byte

**Comment by radarjd** [comment]
Okay, that seems positive for my hypothesis. I just uploaded a new version to PyPi with some error handling. Could you update and run again, please?

**Comment by chanakyan** [comment]
It is working now. Thank you!!

Raj

**Comment by radarjd** [comment]
fixed by adding try / except inside getName()
